# Generated by Django 4.2 on 2024-04-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3)),
                ('description', models.TextField()),
                ('logo_url', models.URLField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
