# Generated by Django 4.2 on 2024-04-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('delete', 'Delete')], default='view', max_length=10),
        ),
    ]
