# Generated by Django 4.2 on 2024-04-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_country_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='action',
        ),
    ]
