# Generated by Django 4.2 on 2024-04-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_country_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
