# Generated by Django 4.2 on 2024-04-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_country_country_name_alter_country_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='status',
            field=models.BooleanField(),
        ),
    ]
